apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
spec:
  containers:
    - name: mem
      image: polinux/stress
      resources:
        limits:
          memory: "20Mi"
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "50M", "--vm-hang", "1"]